db: kadena_events
mongo_uri: ${MONGO_URI}
node: ${NODE_URL}
events:
  - name: coin.TRANSFER
    height: ~
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.ledger.SUPPLY
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.ledger.TOKEN-CREATE
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.ledger.RECONCILE
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.ledger.MINT
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-collection.ADD-TO-COLLECTION
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-collection.CREATE-COLLECTION
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-auction-sale.AUCTION-SALE-OFFER
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-auction-sale.PLACE-BID
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-auction-sale.AUCTION-SALE-BOUGHT
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-auction-sale.AUCTION-SALE-WITHDRAWN
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-fixed-sale.FIXED-SALE-OFFER
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-fixed-sale.FIXED-SALE-BOUGHT
    height: [2300000, ~]
    chains: ["8"]

  - name: n_4e470a97222514a8662dd1219000a0431451b0ee.policy-fixed-sale.FIXED-SALE-WITHDRAWN
    height: [2300000, ~]
    chains: ["8"]

  - name: n_e309f0fa7cf3a13f93a8da5325cdad32790d2070.ktg.CREATE-CONTRACT
    height: [4000000, ~]
    chains: ["2"]

  - name: kaddex.exchange.CREATE_PAIR
    height: [1000000, ~]
    chains: ["2"]

  - name: kaddex.exchange.SWAP
    height: [1000000, ~]
    chains: ["2"]

  - name: kaddex.exchange.UPDATE
    height: [1000000, ~]
    chains: ["2"]

  - name: kdlaunch.kdswap-exchange.CREATE_PAIR
    height: [1000000, ~]
    chains: ["1"]

  - name: kdlaunch.kdswap-exchange.SWAP
    height: [1000000, ~]
    chains: ["1"]

  - name: kdlaunch.kdswap-exchange.UPDATE
    height: [1000000, ~]
    chains: ["1"]

  - name: n_e309f0fa7cf3a13f93a8da5325cdad32790d2070.heron.TRANSFER
    height: [1000000, ~]
    chains: ["2"]



